services:
  - type: web
    name: bizland-app
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
